version: '3'

services:

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
    networks:
      - mynetwrk
  db:
    image: mariadb
    restart:
      on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mydatafiles:/var/lib/mysql
    networks:
      - mynetwrk

networks:
  mynetwrk: {}

volumes:
  mywebfiles:
  mydatafiles:

