version: '3.3'

services:
  # web:
  #   # image: apdapp
  #   # ports:
  #   #   - "8000:80"

  web:
    image: apdwebapp
    build: ../dockerfile/webapp/
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
  
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
