version: '3.3'

services:
  # web:
  #   # image: apdapp
  #   # ports:
  #   #   - "8000:80"

  web:
    image: apdwebapp
    build: ../dockerfile/webapp/
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - /home/apd/projects/prac-web-app/phpapp/:/var/www/html/phpapp/
  
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1

  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
    